# Generated by Django 4.1.13 on 2026-08-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playerachievement'),
        ('coach', '0003_alter_coachprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateField()),
                ('match_title', models.CharField(blank=True, help_text='Opponent or match description (e.g. vs. FC Eagles)', max_length=200, null=True)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('minutes_played', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 / 10'), (2, '2 / 10'), (3, '3 / 10'), (4, '4 / 10'), (5, '5 / 10'), (6, '6 / 10'), (7, '7 / 10'), (8, '8 / 10'), (9, '9 / 10'), (10, '10 / 10')], help_text='Performance rating from 1 (poor) to 10 (outstanding)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Coach comments, fitness notes, tactical observations...', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(blank=True, help_text='Coach who logged this performance record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_performances', to='coach.coachprofile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='players.player')),
            ],
            options={
                'ordering': ['-performance_date', '-created_at'],
            },
        ),
    ]
