# Generated by Django 4.1.13 on 2026-08-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_delete_player'),
        ('players', '0003_playerachievement'),
        ('coach', '0004_playerperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='4-3-3', help_text='Formation name, e.g. 4-3-3', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formation', to='clubs.club')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(help_text='Short key, e.g. GK, LB, CB1, ST', max_length=20)),
                ('label', models.CharField(help_text='Display name, e.g. Goalkeeper, Left-Back', max_length=50)),
                ('top', models.FloatField(help_text='Vertical position (0–100) %')),
                ('left', models.FloatField(help_text='Horizontal position (0–100) %')),
                ('position_hint', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], default='midfielder', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='coach.formation')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineup_slots', to='players.player')),
            ],
            options={
                'ordering': ['slot_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='lineupslot',
            constraint=models.UniqueConstraint(fields=('formation', 'slot_key'), name='unique_slot_per_formation'),
        ),
    ]
