# Generated by Django 4.1.13 on 2026-08-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_formation_lineupslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupslot',
            name='auto_assigned',
            field=models.BooleanField(default=False, help_text='True when this slot was filled automatically by the smart-defaults logic on build'),
        ),
        migrations.AddConstraint(
            model_name='lineupslot',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('formation', 'player'), name='unique_player_per_formation'),
        ),
    ]
