# Generated by Django 4.1.13 on 2026-08-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_lineupslot_auto_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lineupslot',
            name='unique_player_per_formation',
        ),
        migrations.AddConstraint(
            model_name='lineupslot',
            constraint=models.UniqueConstraint(fields=('formation', 'player'), name='unique_player_per_formation'),
        ),
    ]
