# Generated by Django 4.1.13 on 2026-08-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_active_formation'),
        ('coach', '0007_remove_lineupslot_unique_player_per_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formation_type',
            field=models.CharField(choices=[('4-3-3', '4-3-3'), ('4-4-2', '4-4-2'), ('3-5-2', '3-5-2')], default='4-3-3', help_text='Formation shape, e.g. 4-3-3, 4-4-2, 3-5-2', max_length=20),
        ),
        migrations.AlterField(
            model_name='formation',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='clubs.club'),
        ),
    ]
