# Generated by Django 4.1.13 on 2026-08-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_away_score_match_home_score_substitution_goal_and_more'),
        ('coach', '0008_formation_formation_type_alter_formation_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='match',
            field=models.ForeignKey(blank=True, help_text='Link to the Match record (optional for free-form reviews)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_performances', to='matches.match'),
        ),
    ]
