# Generated by Django 4.2.30 on 2026-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coach_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
