# Generated by Django 6.0 on 2026-05-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Software Admin'), ('organizer', 'Tournament Organizer'), ('manager', 'Club Manager'), ('coach', 'Coach'), ('player', 'Player'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
