# Generated by Django 6.0.5 on 2026-05-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_approved_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/citizenship/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/government/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
