# Generated by Django 4.2.30 on 2026-07-23 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_userprofile_coach_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'userprofile__role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
