# Generated by Django 6.0.5 on 2026-05-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_citizenship_document_customuser_club_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_photo',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='club_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='club_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='government_document',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='coach_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/coach_license/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='documents/medical/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizer_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/organizer_letters/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('manager', 'Manager'), ('coach', 'Coach'), ('player', 'Player'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
