# Generated by Django 6.0 on 2026-05-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_photo_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profile_image',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='coach_license',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='medical_report',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organizer_letter',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/government/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_player',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='suspension_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Software Admin'), ('organizer', 'Tournament Organizer'), ('manager', 'Club Manager'), ('coach', 'Coach'), ('player', 'Player'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
