# Generated by Django 6.0 on 2026-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_profile_image_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_active_player',
            new_name='medical_status',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='club_city',
            new_name='pan_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='government_document',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='injured',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pan_document',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='suspension_matches',
        ),
        migrations.AddField(
            model_name='customuser',
            name='authorization_letter',
            field=models.FileField(blank=True, null=True, upload_to='organizers/documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='club_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='coach_license',
            field=models.FileField(blank=True, null=True, upload_to='coach/licenses/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='coach/certificates/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='founded_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='government_registration',
            field=models.FileField(blank=True, null=True, upload_to='clubs/documents/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jersey_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organizer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizers/logos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='citizenship_document',
            field=models.FileField(blank=True, null=True, upload_to='identity/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/logos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('player', 'Player'), ('coach', 'Coach'), ('manager', 'Manager'), ('organizer', 'Organizer')], default='viewer', max_length=20),
        ),
    ]
