# Generated by Django 6.0.5 on 2026-05-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_is_active_player_customuser_medical_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('manager', 'Manager'), ('coach', 'Coach'), ('player', 'Player'), ('viewer', 'Viewer')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=100, null=True)),
                ('organizer_logo', models.ImageField(blank=True, null=True, upload_to='organizer_logos/')),
                ('authorization_letter', models.FileField(blank=True, null=True, upload_to='authorization_letters/')),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('club_name', models.CharField(blank=True, max_length=255, null=True)),
                ('founded_year', models.CharField(blank=True, max_length=20, null=True)),
                ('club_logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('government_registration', models.FileField(blank=True, null=True, upload_to='government_registration/')),
                ('club_address', models.TextField(blank=True, null=True)),
                ('coach_license', models.FileField(blank=True, null=True, upload_to='coach_license/')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='experience_certificates/')),
                ('citizenship_document', models.FileField(blank=True, null=True, upload_to='citizenship_documents/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('jersey_number', models.CharField(blank=True, max_length=10, null=True)),
                ('preferred_position', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
