# Generated by Django 4.1.13 on 2026-07-11 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournaments/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('format', models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout'), ('group_ko', 'Group + Knockout')], max_length=20)),
                ('max_teams', models.IntegerField()),
                ('players_per_team', models.IntegerField()),
                ('prize_first', models.CharField(blank=True, max_length=100)),
                ('prize_second', models.CharField(blank=True, max_length=100)),
                ('prize_third', models.CharField(blank=True, max_length=100)),
                ('rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('registration', 'Registration Open'), ('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='registration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
