# Generated by Django 4.1.13 on 2026-08-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='age_category',
            field=models.CharField(choices=[('all', 'Open (All Ages)'), ('u13', 'Under-13 (U13)'), ('u15', 'Under-15 (U15)'), ('u19', 'Under-19 (U19)'), ('u23', 'Under-23 (U23)'), ('u25', 'Under-25 (U25)')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_best_goalkeeper',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_best_player',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_certificate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_fair_play',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_medals',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_top_scorer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='award_trophy',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='gender_category',
            field=models.CharField(choices=[('men', "Men's Tournament"), ('women', "Women's Tournament"), ('mixed', 'Mixed Category')], default='men', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_type',
            field=models.CharField(choices=[('pre', 'Pre-Registration Only'), ('open', 'Open Registration'), ('invite', 'Invitation Only')], default='open', max_length=20),
        ),
    ]
