# Generated by Django 6.0.5 on 2026-05-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='season',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_type',
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout'), ('group_ko', 'Group + Knockout')], default='knockout', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='players_per_team',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_first',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_second',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_third',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('registration', 'Registration Open'), ('active', 'Active'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
