# Generated by Django 4.1.13 on 2026-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_tournamentregistration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='registration_deadline',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(help_text='Registration closes on this date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(help_text='Registration opens on this date'),
        ),
    ]
