# Generated by Django 4.1.13 on 2026-08-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_remove_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
