# Generated by Django 4.1.13 on 2026-08-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_tournament_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='advancers',
            field=models.PositiveIntegerField(default=0, help_text='Number of teams from this group that advance to the bracket'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='group_label',
            field=models.CharField(blank=True, default='', help_text="Group label (e.g. 'A', 'B') for group+knockout format", max_length=10),
        ),
    ]
