# Generated by Django 4.2.30 on 2026-07-23 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='address',
        ),
        migrations.RemoveField(
            model_name='club',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='club',
            name='government_registration',
        ),
        migrations.RemoveField(
            model_name='club',
            name='pan_number',
        ),
        migrations.AddField(
            model_name='club',
            name='citizenship_document',
            field=models.FileField(blank=True, null=True, upload_to='club_documents/citizenship/'),
        ),
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='government_document',
            field=models.FileField(blank=True, null=True, upload_to='club_documents/govt/'),
        ),
        migrations.AddField(
            model_name='club',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='club_documents/pan/'),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_coaches', to='clubs.club'),
        ),
    ]
