# Generated by Django 4.1.13 on 2026-07-24 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0002_remove_club_address_remove_club_founded_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_id_number',
            field=models.CharField(default='Coach', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='full_name',
            field=models.CharField(default='Coach', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_coach_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
