# Generated by Django 4.1.13 on 2026-08-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_coach_coach_id_number_coach_email_coach_full_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
