# Generated by Django 4.1.13 on 2026-08-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_remove_lineupslot_unique_player_per_formation_and_more'),
        ('clubs', '0004_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='active_formation',
            field=models.ForeignKey(blank=True, help_text='The formation currently in use by this club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='coach.formation'),
        ),
    ]
