# Generated by Django 4.1.13 on 2026-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
