# Generated by Django 4.2.30 on 2026-06-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='jersey_number',
            new_name='preferred_jersey_number',
        ),
    ]
