# Generated by Django 4.1.13 on 2026-06-10 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_rename_jersey_number_player_preferred_jersey_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a 10-digit mobile number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits (e.g., 9876543210).', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_profile_pics/'),
        ),
    ]
