# Generated by Django 4.1.13 on 2026-06-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_club_id'),
        ('players', '0006_alter_player_phone_number_alter_player_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clubs.club'),
        ),
    ]
